---
title: "EDS 223: Week 4"
author: "Josephine Cardelle"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
install.packages("geodata")
library(terra)
library(tidyverse)
library(tmap)
library(kableExtra)
library(spData)
library(spDataLarge)
library(geodata)
install.packages("spDataLarge", repos = "https://nowosad.github.io/drat/", type = "source")
```


```{r}
# create raster objects
zion_elevation <- rast(system.file("raster/srtm.tif", package = "spDataLarge"))

zion_land <- rast(system.file("raster/nlcd.tif", package = "spDataLarge"))

```

```{r}
tm_shape(zion_elevation) +
  tm_raster(title = "Elevation(m)")

tm_shape(zion_land) +
  tm_raster(title = "Land cover")
```

```{r}
landsat <- rast(system.file("raster/landsat.tif", package = "spDataLarge"))
```


```{r}
tm_shape(landsat) + 
  tm_raster()
```

```{r}
landsat3 <- subset(landsat, 3)
```

```{r}
tm_shape(landsat3) + 
  tm_raster()
```

```{r}
global(zion_elevation, mean)
freq(zion_land)
```

## Indexing

```{r}
# row 1, column 1
zion_elevation[1, 1] <- 0
zion_elevation[1]

landsat[1] <- 0

test_raster <- zion_elevation
test_raster[test_raster <20] <- NA
```

## SPATIAL SUBSETTING
```{r}
point <- matrix(c(-113, 37.5), ncol = 2)

terra::extract(zion_elevation, point)

```

```{r}
clip <- rast(xmin = -113.3, xmax = -113, ymin = 37.2, ymax = 37.9,
             resolution = 0.3,
             vals = 1)

zion_elevation_clip <- zion_elevation[clip, drop = FALSE]
```


```{r}
map1 <- tm_shape(zion_elevation) +
  tm_raster(title = "Elevation (m)") +
  tm_layout(main.title = "original")

map2 <- tm_shape(zion_elevation_clip) +
  tm_raster(title = "Elevation (m)") +
    tm_layout(main.title = "clipped")


tmap_arrange(map1, map2, nrow = 1)  
```



```{r}
# Creating mask
rmask <- zion_elevation
rmask[rmask < 2000] <- NA

# bracket subsetting
masked1 <- zion_elevation[rmask, drop = FALSE]
masked2 <- terra::mask(zion_elevation, rmask)

```


```{r}
tm_shape(masked1) +
  tm_raster()
```





```{r}
rcl <- matrix(c(1000, 1500, 1,
                1500, 2000, 2,
                2000, 2500, 3,
                2500, 3000, 4),
              ncol = 3, byrow = TRUE)

reclassified <- terra::classify(zion_elevation, rcl = rcl)
values(reclassified) <- as.factor(values(reclassified))

tm_shape(reclassified) +
  tm_raster()
```


```{r}
ndvi_fun <- function(nir, red){
  (nir - red)/(nir + red)
}

ndvi_rast <- lapp(landsat[[c(4,3)]], fun = ndvi_fun)

tm_shape(ndvi_rast) +
  tm_raster()
```

```{r}
elevation_focal <- focal(zion_elevation,
      w = matrix(1, nrow = 9, ncol = 9),
      fun = min)

map1 <- tm_shape(zion_elevation) +
  tm_raster(title = "Elevation (m)") +
  tm_layout(main.title = "original")

map2 <- tm_shape(elevation_focal) +
  tm_raster(title = "Elevation (m)") +
  tm_layout(main.title = "aggregated")

tmap_arrange(map1, map2, nrow = 1) 
  
```


```{r}
terra::zonal(zion_elevation, reclassified, fun = mean)

```

```{r}
terra::global(zion_elevation, mean)
```


### Changing the extent

```{r}
extend <- terra::extend(zion_elevation, c(1, 200))

extend2 <- terra::extend(zion_elevation, extend)

extend + extend2
```


### Origin
```{r}
origin(zion_elevation)
```

### Changing resolution

```{r}
zion_elevation_coarse <- terra::aggregate(zion_elevation, 
                                          fact = 5,
                                          fun = mean)
map1 <- tm_shape(zion_elevation) +
  tm_raster(title = "Elevation (m)") +
  tm_layout(main.title = "original")

map2 <- tm_shape(zion_elevation_coarse) +
  tm_raster(title = "Elevation (m)") +
  tm_layout(main.title = "aggregated")

tmap_arrange(map1, map2, nrow = 1) 

```


```{r}
# disaggregate the aggregated raster
zion_elevation_disagg <- terra::disagg(zion_elevation_coarse, fact = 5, method = "bilinear")

# check whether the disaggregated version matches the original
if(identical(zion_elevation, zion_elevation_disagg)){
  print("disaggregated data matches original")
} else {
  warning("disaggregated data does not match original")
}
```


### Resampling

```{r}
target_rast <- rast(xmin = -113.2, xmax = -112.9,
                   ymin = 37.14, ymax = 37.5,
                   nrow = 450, ncol = 460, 
                   crs = crs(zion_elevation))

zion_elevation_resample <- terra::resample(zion_elevation, y = target_rast, method = "bilinear")

map4 <- tm_shape(zion_elevation_resample) +
  tm_raster(title = "Elevation (m)") +
  tm_layout(main.title = "resampled")

tmap_arrange(map1, map4, nrow = 1) 
```

